receipt:     Oz-Ware Purchase Invoice
date:        2012-08-06
items:
- 
  part_no:   A4786
  descrip:   Water Bucket (Filled)
  price:     1.47
  quantity:  4

- 
  part_no:   E1628
  descrip:   High Heeled "Ruby" Slippers
  price:     133.7
  quantity:  1

customer:
  given:   Dorothy
  family:  Gale
  table:
        - self
        - lang
        - project
        - user
        - role

log:
  rotate: true
  daily: true
  compress: true
  maxlines: 15000
  maxsize: 100
  maxkeepdays: 7

environments:
    dev:
        url: http://dev.bar.com
        name: Developer Setup
    prod:
        url: http://foo.bar.com
        name: My Cool App
my:
    servers:
        - dev.bar.com
        - foo.bar.com

tom:  |
  Is a cat
  and Jerry is a mouse.
  Ha nobody bike since
  Yellow read.

test: true

server:
    - 120.168.117.21
    - 120.168.117.22
    - 120.168.117.23

kkk: !!str 123
j: !!float    6.8523015e+5

accomplishment: >
 Mark set a major league
 home run record in 1998.

bill-to:          &id001
  street: |
    123 Tornado Alley
    Suite 16
  city:   East Centerville
  state:  KS
  think:  >
     Who am I
     Hello Master.
     Where are you?

ship-to:  *id001

specialDelivery:  >
  Follow the Yellow Brick
  Road to the Emerald City.
  Pay no attention to the
  man behind the curtain.
...